//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.DataAccess
{
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GxSysEntities : DbContext
    {
        public GxSysEntities()
            : base("name=GxSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GX_DICT_CONFIG> GX_DICT_CONFIG { get; set; }
        public DbSet<GX_GKXX> GX_GKXX { get; set; }
        public DbSet<GX_GXRJRELATION> GX_GXRJRELATION { get; set; }
        public DbSet<GX_GXXX> GX_GXXX { get; set; }
        public DbSet<GX_LEAVEOPINION> GX_LEAVEOPINION { get; set; }
        public DbSet<GX_PHOTOGALLERY> GX_PHOTOGALLERY { get; set; }
        public DbSet<GX_RJXX> GX_RJXX { get; set; }
        public DbSet<GX_SYS_MENU> GX_SYS_MENU { get; set; }
        public DbSet<GX_SYS_MODELS> GX_SYS_MODELS { get; set; }
        public DbSet<GX_SYS_PERMISSIONS> GX_SYS_PERMISSIONS { get; set; }
        public DbSet<GX_SYS_ROLE> GX_SYS_ROLE { get; set; }
        public DbSet<GX_SYS_ROLEMENU> GX_SYS_ROLEMENU { get; set; }
        public DbSet<GX_SYS_ROLEPERRELATE> GX_SYS_ROLEPERRELATE { get; set; }
        public DbSet<GX_SYS_USER> GX_SYS_USER { get; set; }
        public DbSet<GX_SYS_USERROLERELATE> GX_SYS_USERROLERELATE { get; set; }
        public DbSet<GX_SYSTEMLOG> GX_SYSTEMLOG { get; set; }
        public DbSet<GX_TASKWORK> GX_TASKWORK { get; set; }
        public DbSet<GX_WFACTIVITYINSTANCE> GX_WFACTIVITYINSTANCE { get; set; }
        public DbSet<GX_WFPROCESS> GX_WFPROCESS { get; set; }
        public DbSet<GX_WFPROCESSINSTANCE> GX_WFPROCESSINSTANCE { get; set; }
        public DbSet<GX_WFTASK> GX_WFTASK { get; set; }
        public DbSet<GX_WFTRANSITIONINSTANCE> GX_WFTRANSITIONINSTANCE { get; set; }
        public DbSet<GX_XLZX> GX_XLZX { get; set; }
        public DbSet<GX_XMYSXX> GX_XMYSXX { get; set; }
        public DbSet<GX_YSZLFILE> GX_YSZLFILE { get; set; }
    }
}
