//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_DICT_CONFIG
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> PARENTID { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string DELETEBY { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
        public string DICTDESC { get; set; }
    }
}
