//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_GXRJRELATION
    {
        public decimal ID { get; set; }
        public Nullable<decimal> GXXXID { get; set; }
        public Nullable<decimal> RJXXID { get; set; }
        public string UPS { get; set; }
        public string ISNEW { get; set; }
        public string JYJGCBH { get; set; }
        public Nullable<decimal> SSGCJH { get; set; }
    }
}
