//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_GXXX
    {
        public decimal ID { get; set; }
        public Nullable<decimal> XMYSXXID { get; set; }
        public string GCBH { get; set; }
        public string GXWZ { get; set; }
        public Nullable<decimal> GXCD { get; set; }
        public string DXLX { get; set; }
        public string GXLX { get; set; }
        public string JSZT { get; set; }
        public string YWLX { get; set; }
        public string GJZ { get; set; }
        public string XNZC { get; set; }
        public string GKCL { get; set; }
        public Nullable<decimal> SYZT { get; set; }
        public Nullable<decimal> GKHS { get; set; }
        public Nullable<decimal> GKLS { get; set; }
        public Nullable<decimal> PLSX { get; set; }
        public string GXZT { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string DELETEBY { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
        public string GH { get; set; }
        public Nullable<decimal> JJ { get; set; }
        public string STQK { get; set; }
        public string QJ { get; set; }
        public string ZJ { get; set; }
        public string QJGKWZ { get; set; }
        public string ZJGKWZ { get; set; }
    }
}
