//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_gxxx
    {
        public int Id { get; set; }
        public int xmysxxid { get; set; }
        public string GCBH { get; set; }
        public string gxwz { get; set; }
        public Nullable<double> gxcd { get; set; }
        public string dxlx { get; set; }
        public string gxlx { get; set; }
        public string jszt { get; set; }
        public string ywlx { get; set; }
        public string gjz { get; set; }
        public string xnzc { get; set; }
        public string gkcl { get; set; }
        public Nullable<int> syzt { get; set; }
        public Nullable<int> gkhs { get; set; }
        public Nullable<int> gkls { get; set; }
        public Nullable<int> plsx { get; set; }
        public string qjwz { get; set; }
        public string zjwz { get; set; }
        public Nullable<bool> gxzt { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string modify { get; set; }
        public Nullable<System.DateTime> modifytime { get; set; }
        public string deleteby { get; set; }
        public Nullable<System.DateTime> deletetime { get; set; }
    }
}
