//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_photogallery
    {
        public int Id { get; set; }
        public int parentId { get; set; }
        public string tpbh { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> tjsj { get; set; }
        public Nullable<bool> sfyx { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
