//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_RJXX
    {
        public decimal ID { get; set; }
        public Nullable<decimal> XMYSXXID { get; set; }
        public string GCBH { get; set; }
        public string RJBH { get; set; }
        public string RJMC { get; set; }
        public string GCRJBH { get; set; }
        public Nullable<decimal> JGSL { get; set; }
        public string DXLX { get; set; }
        public string RSJCC { get; set; }
        public string JGLX { get; set; }
        public string GJZ { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string RJZT { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
        public string DELETEBY { get; set; }
    }
}
