//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_rjxx
    {
        public Nullable<int> xmysxxid { get; set; }
        public string gcbh { get; set; }
        public string rjbh { get; set; }
        public string rjmc { get; set; }
        public string gcrjbh { get; set; }
        public Nullable<int> jgsl { get; set; }
        public string dxlx { get; set; }
        public string rsjcc { get; set; }
        public string jglx { get; set; }
        public string gjz { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public Nullable<bool> rjzt { get; set; }
        public string modify { get; set; }
        public Nullable<System.DateTime> modifyTime { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> deletetime { get; set; }
        public string deleteby { get; set; }
        public int Id { get; set; }
    }
}
