//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_sys_permissions
    {
        public int Id { get; set; }
        public string perName { get; set; }
        public string perDesc { get; set; }
        public Nullable<int> perStatus { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string modify { get; set; }
        public Nullable<System.DateTime> modifytime { get; set; }
    }
}
