//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_sys_user
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public string userCode { get; set; }
        public string userName { get; set; }
        public string userpwd { get; set; }
        public string userMobile { get; set; }
        public string userEmail { get; set; }
        public string userSex { get; set; }
        public Nullable<int> userStatus { get; set; }
        public string loginIp { get; set; }
        public Nullable<System.DateTime> loginTime { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string modify { get; set; }
        public Nullable<System.DateTime> modifytime { get; set; }
        public string deleteby { get; set; }
        public Nullable<System.DateTime> deletetime { get; set; }
    }
}
