//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_SYS_USER
    {
        public decimal ID { get; set; }
        public string USERID { get; set; }
        public string USERCODE { get; set; }
        public string USERNAME { get; set; }
        public string USERPWD { get; set; }
        public string USERMOBILE { get; set; }
        public string USEREMAIL { get; set; }
        public string USERSEX { get; set; }
        public Nullable<decimal> USERSTATUS { get; set; }
        public string LOGINIP { get; set; }
        public Nullable<System.DateTime> LOGINTIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string DELETEBY { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
    }
}
