//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_SYS_MENU
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MODELID { get; set; }
        public string MENUNAMC { get; set; }
        public string MENUURL { get; set; }
        public string MENUBZ { get; set; }
        public Nullable<decimal> MENUPARENTID { get; set; }
        public Nullable<decimal> MENUSTATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYBY { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string DELETEBY { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
    }
}
