//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_SYSTEMLOG
    {
        public decimal ID { get; set; }
        public string MENUURL { get; set; }
        public Nullable<System.DateTime> TIMEFLAG { get; set; }
        public string ACTNAME { get; set; }
        public string CONTENTS { get; set; }
        public string ACTUSERCODE { get; set; }
        public string ACTRESULT { get; set; }
    }
}
