//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_taskwork
    {
        public int Id_任务分配表标识 { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> gx__Id { get; set; }
        public Nullable<int> gx__Id2 { get; set; }
        public Nullable<int> xmysxxid { get; set; }
        public string userid { get; set; }
        public Nullable<int> xlzxId { get; set; }
    }
}
