//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_wftransitionInstance
    {
        public int Id { get; set; }
        public string TransitionGUID { get; set; }
        public Nullable<int> ProcessInstanceID { get; set; }
        public string ProcessGUID { get; set; }
        public Nullable<byte> TransitionType { get; set; }
        public Nullable<byte> FlyingType { get; set; }
        public Nullable<int> FromActivityInstanceID { get; set; }
        public string FromActivityGUID { get; set; }
        public Nullable<short> FromActivityType { get; set; }
        public string FromActivityName { get; set; }
        public Nullable<int> ToActivityInstanceID { get; set; }
        public string ToActivityGUID { get; set; }
        public Nullable<short> ToActivityType { get; set; }
        public string ToActivityName { get; set; }
        public Nullable<byte> ConditionParseResult { get; set; }
        public string CreatedByUserID { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<byte> RecordStatusInvalid { get; set; }
        public byte[] RowVersionID { get; set; }
        public Nullable<int> AppinstanceId { get; set; }
        public string AppInstanceCode { get; set; }
    }
}
