//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_WFPROCESS
    {
        public decimal ID { get; set; }
        public string PROCESSGUID { get; set; }
        public string PROCESSNAME { get; set; }
        public string VERSION { get; set; }
        public string ISUSING { get; set; }
        public string XMLFILENAME { get; set; }
        public string XMLFILEPATH { get; set; }
        public string XMLCONTENT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public Nullable<System.DateTime> ROWVERSIONID { get; set; }
    }
}
