//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_WFACTIVITYINSTANCE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PROCESSINSTANCEID { get; set; }
        public Nullable<decimal> APPINSTANCEID { get; set; }
        public string APPNAME { get; set; }
        public string APPINSTANCECODE { get; set; }
        public string PROCESSGUID { get; set; }
        public string ACTIVITYGUID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public Nullable<short> ACTIVITYTYPE { get; set; }
        public Nullable<short> ACTIVITYSTATE { get; set; }
        public string ASSIGNEDTOUSERIDS { get; set; }
        public string ASSIGNEDTOUSERNAMES { get; set; }
        public Nullable<short> BACKWARDTYPE { get; set; }
        public Nullable<decimal> BACKSRCACTIVITYINSTANCEID { get; set; }
        public Nullable<short> GATEWAYDIRECTIONTYPEID { get; set; }
        public Nullable<decimal> CANRENEWINSTANCE { get; set; }
        public Nullable<decimal> TOKENSREQUIRED { get; set; }
        public Nullable<decimal> TOKENSHAD { get; set; }
        public Nullable<short> COMPLEXTYPE { get; set; }
        public Nullable<decimal> MIHOSTACTIVITYINSTANCEID { get; set; }
        public Nullable<decimal> COMPLETEORDER { get; set; }
        public Nullable<short> SIGNFORWARDTYPE { get; set; }
        public string CREATEDBYUSERID { get; set; }
        public string CREATEDBYUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string LASTUPDATEDBYUSERID { get; set; }
        public string LASTUPDATEDBYUSERNAME { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public Nullable<System.DateTime> ENDEDDATETIME { get; set; }
        public string ENDEDBYUSERID { get; set; }
        public string ENDEDBYUSERNAME { get; set; }
        public Nullable<decimal> RECORDSTATUSINVALID { get; set; }
        public Nullable<System.DateTime> ROWVERSIONID { get; set; }
    }
}
