//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_wftask
    {
        public int Id { get; set; }
        public Nullable<int> ActivityInstanceID { get; set; }
        public Nullable<int> ProcessInstanceID { get; set; }
        public string AppName { get; set; }
        public Nullable<int> AppInstanceId { get; set; }
        public string ProcessGUID { get; set; }
        public string ActivityGUID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<short> TaskType { get; set; }
        public Nullable<short> TaskState { get; set; }
        public string AssignedToUserID { get; set; }
        public string AssignedToUserName { get; set; }
        public string CreatedByUserID { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string LastUpdatedByUserID { get; set; }
        public string LastUpdatedByUserName { get; set; }
        public string EndedByUserID { get; set; }
        public string EndedByUserName { get; set; }
        public Nullable<System.DateTime> EndedDateTime { get; set; }
        public Nullable<byte> RecordStatusInvalid { get; set; }
        public byte[] RowVersionID { get; set; }
    }
}
