//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_WFTRANSITIONINSTANCE
    {
        public decimal ID { get; set; }
        public string TRANSITIONGUID { get; set; }
        public Nullable<decimal> PROCESSINSTANCEID { get; set; }
        public string PROCESSGUID { get; set; }
        public Nullable<decimal> TRANSITIONTYPE { get; set; }
        public Nullable<decimal> FLYINGTYPE { get; set; }
        public Nullable<decimal> FROMACTIVITYINSTANCEID { get; set; }
        public string FROMACTIVITYGUID { get; set; }
        public Nullable<decimal> FROMACTIVITYTYPE { get; set; }
        public string FROMACTIVITYNAME { get; set; }
        public Nullable<decimal> TOACTIVITYINSTANCEID { get; set; }
        public string TOACTIVITYGUID { get; set; }
        public Nullable<decimal> TOACTIVITYTYPE { get; set; }
        public string TOACTIVITYNAME { get; set; }
        public Nullable<decimal> CONDITIONPARSERESULT { get; set; }
        public string CREATEDBYUSERID { get; set; }
        public string CREATEDBYUSERNAME { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<decimal> RECORDSTATUSINVALID { get; set; }
        public Nullable<System.DateTime> ROWVERSIONID { get; set; }
        public Nullable<decimal> APPINSTANCEID { get; set; }
        public string APPINSTANCECODE { get; set; }
    }
}
