//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_WFPROCESSINSTANCE
    {
        public decimal ID { get; set; }
        public string PROCESSGUID { get; set; }
        public string PROCESSNAME { get; set; }
        public string VERSION { get; set; }
        public Nullable<decimal> APPINSTANCEID { get; set; }
        public string APPNAME { get; set; }
        public string APPINSTANCECODE { get; set; }
        public Nullable<decimal> PROCESSSTATE { get; set; }
        public Nullable<decimal> PARENTPROCESSINSTANCEID { get; set; }
        public string PARENTPROCESSGUID { get; set; }
        public Nullable<decimal> INVOKEDACTIVITYINSTANCEID { get; set; }
        public string INVOKEDACTIVITYGUID { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public string CREATEDBYUSERID { get; set; }
        public string CREATEDBYUSERNAME { get; set; }
        public Nullable<System.DateTime> LASTUPDATEDDATETIME { get; set; }
        public string LASTUPDATEDBYUSERID { get; set; }
        public string LASTUPDATEDBYUSERNAME { get; set; }
        public Nullable<System.DateTime> ENDEDDATETIME { get; set; }
        public string ENDEDBYUSERID { get; set; }
        public string ENDEDBYUSERNAME { get; set; }
        public Nullable<decimal> RECORDSTATUSINVALID { get; set; }
        public Nullable<System.DateTime> ROWVERSIONID { get; set; }
    }
}
