//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_wfactivityinstance
    {
        public int Id { get; set; }
        public Nullable<int> gx__Id { get; set; }
        public Nullable<int> gx__Id2 { get; set; }
        public Nullable<int> ProcessInstanceID { get; set; }
        public Nullable<int> AppinstanceId { get; set; }
        public string AppName { get; set; }
        public string AppInstanceCode { get; set; }
        public string ProcessGUID { get; set; }
        public string ActivityGUID { get; set; }
        public string ActivityName { get; set; }
        public Nullable<short> ActivityType { get; set; }
        public Nullable<short> ActivityState { get; set; }
        public string AssignedToUserIDs { get; set; }
        public string AssignedToUserNames { get; set; }
        public Nullable<short> BackwardType_退回类型 { get; set; }
        public Nullable<int> BackSrcActivityInstanceID { get; set; }
        public Nullable<short> GatewayDirectionTypeID { get; set; }
        public Nullable<byte> CanRenewInstance { get; set; }
        public Nullable<int> TokensRequired { get; set; }
        public Nullable<int> TokensHad { get; set; }
        public Nullable<short> ComplexType { get; set; }
        public Nullable<int> MIHostActivityInstanceID { get; set; }
        public Nullable<double> CompleteOrder { get; set; }
        public Nullable<short> SignForwardType { get; set; }
        public string CreatedByUserID { get; set; }
        public string CreatedByUserName { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string LastUpdatedByUserID { get; set; }
        public string LastUpdatedByUserName { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public Nullable<System.DateTime> EndedDateTime { get; set; }
        public string EndedByUserID { get; set; }
        public string EndedByUserName { get; set; }
        public Nullable<byte> RecordStatusInvalid { get; set; }
        public byte[] RowVersionID { get; set; }
    }
}
