//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_wfprocess
    {
        public int Id { get; set; }
        public string processguid { get; set; }
        public string processname { get; set; }
        public string version { get; set; }
        public Nullable<bool> isusing { get; set; }
        public string XmlFileName { get; set; }
        public string XmlFilePath { get; set; }
        public string XmlContent { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public byte[] RowVersionID { get; set; }
    }
}
