//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_XMYSXX
    {
        public decimal ID { get; set; }
        public string HTBH { get; set; }
        public string GCMC { get; set; }
        public string GCBH { get; set; }
        public string SGDWMC { get; set; }
        public string JLDWDM { get; set; }
        public Nullable<decimal> YSZT { get; set; }
        public Nullable<System.DateTime> HTSJ { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string YSRY { get; set; }
        public string XLZX { get; set; }
    }
}
