//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GX_YSZLFILE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> XMYSXXID { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string FILENAME { get; set; }
        public string FILEURL { get; set; }
        public Nullable<decimal> FILESIZE { get; set; }
        public string FILEZT { get; set; }
        public Nullable<System.DateTime> UPLOADTIME { get; set; }
        public string CREATEBY { get; set; }
        public string ADELETEBY { get; set; }
        public Nullable<System.DateTime> DELETETIME { get; set; }
    }
}
