//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gx_yszlfile
    {
        public int Id { get; set; }
        public int xmysxxid { get; set; }
        public int type { get; set; }
        public string filename { get; set; }
        public string fileurl { get; set; }
        public Nullable<int> filesize { get; set; }
        public Nullable<bool> filezt { get; set; }
        public Nullable<System.DateTime> uploadtime { get; set; }
        public string createby { get; set; }
        public string adeleteby { get; set; }
        public Nullable<System.DateTime> deletetime { get; set; }
    }
}
